apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
 name: spark-pi
 namespace: spark-jobs
spec:
 type: Python
 mode: cluster
 image: "apache/spark:3.5.1"
 imagePullPolicy: Always
 mainApplicationFile: "local:///opt/spark/examples/src/main/python/pi.py"
 sparkVersion: "3.5.1"
 restartPolicy:
   type: Never
 volumes:
   - name: "test-volume"
     hostPath:
       path: "/tmp"
       type: Directory
 driver:
   cores: 1
   coreLimit: "1200m"
   memory: "512m"
   labels:
     version: 3.5.1
   serviceAccount: spark
   volumeMounts:
     - name: "test-volume"
       mountPath: "/tmp"
 executor:
   cores: 1
   instances: 2
   memory: "512m"
   labels:
     version: 3.5.1
   serviceAccount: spark
   volumeMounts:
     - name: "test-volume"
       mountPath: "/tmp"